Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [6]:
# solution
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print('the data type of list variable', type(list_))
print('the data type of array_list variable',type(array_list))

the data type of list variable <class 'list'>
the data type of array_list variable <class 'numpy.ndarray'>


In [15]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print('the data type of list_variable')
for element in list_:
    print(type(list_))
    
print('the data type of array_list variable')
for element in np.nditer(array_list):
    print(type(element.item())    )
    

the data type of list_variable
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
the data type of array_list variable
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
'''
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)'''

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_,dtype=int)
# letscheck
print('the data type of list_variable is')
for element in list_:
    print(type(element))
    
print('the data type of array_list ') 
for element in np.nditer(array_list):
    print(type(element.item()))   

the data type of list_variable is
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
the data type of array_list 
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [ ]:
'''Yes, there will be a difference in the data types of the elements present in both variables list_ and array_list.

In the variable array_list, the data type of the elements will be converted to integers because of the dtype=int 
argument in the np.array() function. However, in variable list_, the elements remain strings.'''

In [18]:
'''Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size '''

'Consider the below code to answer further questions:\nimport numpy as np\nnum_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]\nnum_array = np.array(object = num_list)\nQ4. Write a code to find the following characteristics of variable, num_array:\n(i) shape\n(ii) size '

In [23]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array
# (i) shape : tells the how many row and columns in the array
num_array.shape

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# (ii) size : tells the how many element present in the array
num_array.size

6

In [26]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]'''

# answer 
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])